name: Secure Container Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t secure-fastapi .

      - name: Install Trivy
        run: |
          sudo apt-get install wget -y
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.63.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.63.0_Linux-64bit.deb

      - name: Scan image for vulnerabilities
        run: |
          trivy image --exit-code 1 --severity HIGH,CRITICAL secure-fastapi