name: Secure Container Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Build Docker image
        run: docker build -t secure-fastapi .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'secure-fastapi'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'